// POII domain schema (BUILD-BASELINE.md §5, ADR-0005). Changing this file is a gated change.
// Every table carries a workspace id. Ids are UUIDv7 generated by the API, never by the database.
import { sql } from 'drizzle-orm';
import {
  boolean, check, customType, index, integer, jsonb, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid,
  type AnyPgColumn,
} from 'drizzle-orm/pg-core';

const tsvector = customType<{ data: string }>({ dataType: () => 'tsvector' });

export const actorKind = pgEnum('actor_kind', ['person', 'ai_assistant', 'agent_token', 'system']);
export const authority = pgEnum('authority', ['owner', 'delegated']);
export const sourceKind = pgEnum('source_kind', ['paste', 'upload', 'import']);
export const recordKind = pgEnum('record_kind', ['fact', 'requirement', 'decision', 'question']);
export const reviewState = pgEnum('review_state', ['candidate', 'confirmed', 'rejected']);
export const lifecycleStatus = pgEnum('lifecycle_status', ['proposed', 'decided', 'implemented', 'observed', 'unknown']);
export const statedRole = pgEnum('stated_role', ['owner', 'assistant', 'third_party', 'unknown']);
export const statementMode = pgEnum('statement_mode', ['quoted', 'pasted', 'paraphrased', 'ai_extracted']);
export const timeStatus = pgEnum('time_status', ['known', 'unknown', 'not_applicable', 'conflicting']);
export const evidenceRole = pgEnum('evidence_role', ['primary', 'supporting']);
export const anchorResult = pgEnum('anchor_result', ['exact', 'moved', 'lost']);
export const changeKind = pgEnum('change_kind', ['create', 'edit', 'confirm', 'reject', 'supersede', 'status', 'evidence']);
export const exportKind = pgEnum('export_kind', ['context_pack', 'backup']);

export const instanceInfo = pgTable('instance_info', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export const workspace = pgTable('workspace', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/** People, AI assistants, agent tokens and the system. Only persons can carry authority. */
export const actor = pgTable('actor', {
  id: uuid('id').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  kind: actorKind('kind').notNull(),
  displayName: text('display_name').notNull(),
  /** Null for everything except persons with authority. Enforced in the service and by the check below. */
  authority: authority('authority'),
  /** For ai_assistant: provider and model; for agent_token: scopes; for persons: identity bindings live elsewhere. */
  details: jsonb('details').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  revokedAt: timestamp('revoked_at', { withTimezone: true }),
}, table => [
  index('actor_workspace_idx').on(table.workspaceId),
  // A non-person actor can never hold authority.
  check('actor_authority_persons_only', sql`${table.kind} = 'person' OR ${table.authority} IS NULL`),
]);

/** An imported original. Content lives in immutable revisions. */
export const source = pgTable('source', {
  id: uuid('id').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  title: text('title').notNull(),
  kind: sourceKind('kind').notNull(),
  mediaType: text('media_type').notNull().default('text/plain'),
  /** Platform, conversation id, URL, file name, importer: whatever identifies where this came from. Data, not instructions. */
  origin: jsonb('origin').$type<Record<string, unknown>>().notNull().default({}),
  /** Stable key for idempotent re-import (for example "chatgpt:conversation:<id>"). Null for plain pastes. */
  originKey: text('origin_key'),
  /** false = never send to AI. Inherited by every derived record. */
  aiAllowed: boolean('ai_allowed').notNull().default(true),
  archivedAt: timestamp('archived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdByActorId: uuid('created_by_actor_id').notNull().references(() => actor.id),
}, table => [
  index('source_workspace_idx').on(table.workspaceId),
  uniqueIndex('source_origin_key_unique').on(table.workspaceId, table.originKey),
]);

export const sourceRevision = pgTable('source_revision', {
  id: uuid('id').primaryKey(),
  sourceId: uuid('source_id').notNull().references(() => source.id, { onDelete: 'cascade' }),
  revisionNo: integer('revision_no').notNull(),
  contentText: text('content_text').notNull(),
  contentSha256: text('content_sha256').notNull(),
  byteLength: integer('byte_length').notNull(),
  lineCount: integer('line_count').notNull(),
  /** Key of the untouched original bytes in the storage port, when uploaded. */
  storageKey: text('storage_key'),
  note: text('note'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdByActorId: uuid('created_by_actor_id').notNull().references(() => actor.id),
  searchVector: tsvector('search_vector').generatedAlwaysAs(sql`to_tsvector('english', content_text)`),
}, table => [
  uniqueIndex('source_revision_no_unique').on(table.sourceId, table.revisionNo),
  uniqueIndex('source_revision_hash_unique').on(table.sourceId, table.contentSha256),
  index('source_revision_search_idx').using('gin', table.searchVector),
]);

/** Left behind by a hard delete so exports can say "unavailable" and re-imports stay idempotent. */
export const sourceTombstone = pgTable('source_tombstone', {
  id: uuid('id').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  originKey: text('origin_key'),
  lastContentSha256: text('last_content_sha256'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }).notNull().defaultNow(),
  deletedByActorId: uuid('deleted_by_actor_id').notNull().references(() => actor.id),
  reason: text('reason'),
});

/** A fact, requirement, decision or question. Attribution here; approval in `approval`. */
export const record = pgTable('record', {
  id: uuid('id').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  kind: recordKind('kind').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull().default(''),
  reviewState: reviewState('review_state').notNull().default('candidate'),
  lifecycleStatus: lifecycleStatus('lifecycle_status').notNull().default('unknown'),
  // Attribution: who said it, in what role, how it reached POII.
  statedByActorId: uuid('stated_by_actor_id').references(() => actor.id),
  statedRole: statedRole('stated_role').notNull().default('unknown'),
  statementMode: statementMode('statement_mode').notNull(),
  // Three times. recorded_at is always known.
  recordedAt: timestamp('recorded_at', { withTimezone: true }).notNull().defaultNow(),
  effectiveAt: timestamp('effective_at', { withTimezone: true }),
  effectiveAtStatus: timeStatus('effective_at_status').notNull().default('unknown'),
  observedAt: timestamp('observed_at', { withTimezone: true }),
  observedAtStatus: timeStatus('observed_at_status').notNull().default('not_applicable'),
  /** Competing values when a time status is `conflicting`: [{ value, sourceId, note }]. */
  timeConflicts: jsonb('time_conflicts').$type<Array<Record<string, unknown>>>(),
  supersedesRecordId: uuid('supersedes_record_id').references((): AnyPgColumn => record.id),
  rejectedAt: timestamp('rejected_at', { withTimezone: true }),
  rejectionReason: text('rejection_reason'),
  /** Maintained from evidence: false when any cited source is never-send-to-AI. */
  aiAllowed: boolean('ai_allowed').notNull().default(true),
  /** ADR-0001: origin system, id and version when this record was copied or promoted from a peer. */
  origin: jsonb('origin').$type<Record<string, unknown>>(),
  versionNo: integer('version_no').notNull().default(1),
  createdByActorId: uuid('created_by_actor_id').notNull().references(() => actor.id),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  searchVector: tsvector('search_vector').generatedAlwaysAs(sql`to_tsvector('english', title || ' ' || body)`),
}, table => [
  index('record_workspace_idx').on(table.workspaceId),
  index('record_kind_state_idx').on(table.workspaceId, table.kind, table.reviewState),
  index('record_supersedes_idx').on(table.supersedesRecordId),
  index('record_search_idx').using('gin', table.searchVector),
]);

export const recordVersion = pgTable('record_version', {
  id: uuid('id').primaryKey(),
  recordId: uuid('record_id').notNull().references(() => record.id, { onDelete: 'cascade' }),
  versionNo: integer('version_no').notNull(),
  changeKind: changeKind('change_kind').notNull(),
  snapshot: jsonb('snapshot').$type<Record<string, unknown>>().notNull(),
  changedByActorId: uuid('changed_by_actor_id').notNull().references(() => actor.id),
  changedAt: timestamp('changed_at', { withTimezone: true }).notNull().defaultNow(),
  note: text('note'),
}, table => [uniqueIndex('record_version_unique').on(table.recordId, table.versionNo)]);

/** Link from a record to a span in a source revision. Survives source deletion as "unavailable". */
export const recordEvidence = pgTable('record_evidence', {
  id: uuid('id').primaryKey(),
  recordId: uuid('record_id').notNull().references(() => record.id, { onDelete: 'cascade' }),
  sourceId: uuid('source_id').references(() => source.id, { onDelete: 'set null' }),
  originalSourceId: uuid('original_source_id').notNull(),
  revisionId: uuid('revision_id').references(() => sourceRevision.id, { onDelete: 'set null' }),
  /** packages/contracts Locator. */
  locator: jsonb('locator').$type<Record<string, unknown>>().notNull(),
  role: evidenceRole('role').notNull().default('primary'),
  anchorResult: anchorResult('anchor_result').notNull().default('exact'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, table => [
  index('record_evidence_record_idx').on(table.recordId),
  index('record_evidence_source_idx').on(table.sourceId),
]);

/** A person with authority confirming a record. The only way a record becomes confirmed. */
export const approval = pgTable('approval', {
  id: uuid('id').primaryKey(),
  recordId: uuid('record_id').notNull().references(() => record.id, { onDelete: 'cascade' }),
  approvedByActorId: uuid('approved_by_actor_id').notNull().references(() => actor.id),
  authority: authority('authority').notNull(),
  approvedAt: timestamp('approved_at', { withTimezone: true }).notNull().defaultNow(),
  /** The exact record this approval replaces, if any. */
  antecedentRecordId: uuid('antecedent_record_id').references(() => record.id),
  note: text('note'),
}, table => [index('approval_record_idx').on(table.recordId)]);

export const auditEvent = pgTable('audit_event', {
  id: uuid('id').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  actorId: uuid('actor_id').references(() => actor.id),
  action: text('action').notNull(),
  targetType: text('target_type').notNull(),
  targetId: uuid('target_id'),
  requestId: text('request_id'),
  details: jsonb('details').$type<Record<string, unknown>>().notNull().default({}),
  at: timestamp('at', { withTimezone: true }).notNull().defaultNow(),
}, table => [index('audit_event_target_idx').on(table.targetType, table.targetId)]);

/** Stored result of a mutating request so a retry returns the first outcome. */
export const idempotencyKey = pgTable('idempotency_key', {
  key: text('key').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  requestSha256: text('request_sha256').notNull(),
  status: integer('status').notNull(),
  response: jsonb('response').$type<unknown>().notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export const exportRun = pgTable('export_run', {
  id: uuid('id').primaryKey(),
  workspaceId: uuid('workspace_id').notNull().references(() => workspace.id),
  kind: exportKind('kind').notNull(),
  formatVersion: integer('format_version').notNull(),
  selection: jsonb('selection').$type<Record<string, unknown>>().notNull().default({}),
  manifest: jsonb('manifest').$type<Record<string, unknown>>().notNull(),
  contentSha256: text('content_sha256').notNull(),
  storageKey: text('storage_key'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  createdByActorId: uuid('created_by_actor_id').notNull().references(() => actor.id),
});
export * from './ai.js'; // #13 AI

// #16 ops
export * from './ops.js';
