import { createHash } from 'node:crypto';
import { v7 } from 'uuid';
import type { z } from 'zod';

/** UUIDv7: time-ordered, generated by the API (BUILD-BASELINE.md §5). */
export const newId = (): string => v7();

export const sha256Hex = (data: string | Uint8Array): string => createHash('sha256').update(data).digest('hex');

export function iso(value: Date): string;
export function iso(value: Date | null | undefined): string | null;
export function iso(value: Date | null | undefined): string | null {
  return value ? value.toISOString() : null;
}

export const toDate = (value: string | null | undefined): Date | null => (value ? new Date(value) : null);

/** JSON with sorted object keys, so equal values hash equally. */
export function canonicalJson(value: unknown): string {
  return JSON.stringify(sortKeys(value));
}

function sortKeys(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortKeys);
  if (value instanceof Date) return value.toISOString();
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value as Record<string, unknown>).sort()) {
      const item = (value as Record<string, unknown>)[key];
      if (item !== undefined) out[key] = sortKeys(item);
    }
    return out;
  }
  return value;
}

/** Validates with a contract schema; a failure becomes 400 validation_failed in the exception filter. */
export function parse<S extends z.ZodType>(schema: S, data: unknown): z.output<S> {
  return schema.parse(data ?? {});
}

export function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) out.push(items.slice(i, i + size));
  return out;
}
